# Generated by Django 5.1.1 on 2024-10-13 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='date_of_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_testdrive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='number_of_support_staff',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='company',
            name='paid_machines_quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
