# Generated by Django 5.1.1 on 2024-10-13 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0003_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('indent', models.IntegerField(default=0)),
                ('areas_quantity', models.IntegerField(default=0)),
                ('machines_quantity', models.IntegerField(default=0)),
                ('operators_quantity', models.IntegerField(default=0)),
                ('support_stuff_quantity', models.IntegerField(default=0)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebSite.field')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WebSite.user')),
            ],
            options={
                'db_table': 'Department',
            },
        ),
    ]
