# Generated by Django 5.1.1 on 2024-10-13 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0005_area_allocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firstmachinetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Firstmachinetype',
            },
        ),
        migrations.CreateModel(
            name='Secondmachinetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Secondmachinetype',
            },
        ),
        migrations.CreateModel(
            name='Shiftschedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_change', models.TimeField(blank=True, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('time_first', models.TimeField(blank=True, null=True)),
                ('days', models.IntegerField(blank=True, null=True)),
                ('info', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Shiftschedule',
            },
        ),
        migrations.CreateModel(
            name='Detailmachinetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('first_machine_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WebSite.firstmachinetype')),
            ],
            options={
                'db_table': 'Detailmachinetype',
            },
        ),
    ]
