# Generated by Django 5.1.1 on 2024-10-13 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0009_chiefbatch_stage_operation_chiefdistribution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stagestatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Stagestatus',
            },
        ),
        migrations.CreateModel(
            name='Stagedistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chief_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WebSite.chiefbatch')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WebSite.department')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebSite.stage')),
                ('stage_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WebSite.stagestatus')),
            ],
            options={
                'db_table': 'Stagedistribution',
            },
        ),
    ]
