# Generated by Django 5.1.1 on 2024-10-13 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0010_stagestatus_stagedistribution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chiefoperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_distributed', models.BooleanField(default=False)),
                ('chief_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebSite.chiefbatch')),
                ('distribution_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WebSite.stagedistribution')),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WebSite.operation')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WebSite.stage')),
            ],
            options={
                'db_table': 'Chiefoperation',
            },
        ),
        migrations.CreateModel(
            name='Stagearchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('batch_archive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WebSite.batcharchive')),
            ],
            options={
                'db_table': 'Stagearchive',
            },
        ),
    ]
