# Generated by Django 5.1.1 on 2024-10-13 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0011_chiefoperation_stagearchive'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operationarchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
                ('time_pz', models.DurationField(blank=True, null=True)),
                ('time_sh', models.DurationField(blank=True, null=True)),
                ('stage_archive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WebSite.stagearchive')),
            ],
            options={
                'db_table': 'Operationarchive',
            },
        ),
        migrations.CreateModel(
            name='Operationoperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_plan', models.DurationField(blank=True, null=True)),
                ('time_first_start', models.DateTimeField(blank=True, null=True)),
                ('time_start', models.DateTimeField(blank=True, null=True)),
                ('time_stop', models.DateTimeField(blank=True, null=True)),
                ('time_working', models.DurationField(blank=True, null=True)),
                ('pause', models.BooleanField(blank=True, null=True)),
                ('optimal_part', models.CharField(blank=True, max_length=255, null=True)),
                ('modific', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WebSite.area')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WebSite.batch')),
                ('chief_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WebSite.chiefbatch')),
                ('chief_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WebSite.chiefoperation')),
                ('distribution_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WebSite.stagedistribution')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WebSite.machine')),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WebSite.operation')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WebSite.order')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WebSite.user')),
                ('stage_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WebSite.stagestatus')),
            ],
            options={
                'db_table': 'Operationoperator',
            },
        ),
    ]
