# Generated by Django 5.1.1 on 2024-10-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0012_operationarchive_operationoperator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporttype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Reporttype',
            },
        ),
    ]
