# Generated by Django 5.1.1 on 2024-10-13 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0013_reporttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shiftdistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('change', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WebSite.shift')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WebSite.machine')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WebSite.user')),
            ],
            options={
                'db_table': 'Shiftdistribution',
            },
        ),
    ]
