# Generated by Django 5.1.1 on 2024-10-13 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0016_transferarchive_transferoperation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uploadedreport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default=0, max_length=100)),
                ('report_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WebSite.reporttype')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WebSite.user')),
            ],
            options={
                'db_table': 'Uploadedreport',
            },
        ),
        migrations.CreateModel(
            name='Workershift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.DateTimeField()),
                ('time_end', models.DateTimeField(blank=True, null=True)),
                ('isactive', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('change', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='WebSite.shift')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='WebSite.user')),
            ],
            options={
                'db_table': 'Workershift',
            },
        ),
    ]
