# Generated by Django 5.1.1 on 2024-10-13 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0017_uploadedreport_workershift'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebSite.area')),
            ],
            options={
                'db_table': 'Subdivision',
            },
        ),
    ]
