# Generated by Django 5.1.1 on 2024-10-13 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0019_remove_user_company_user_subdivision'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='field',
            options={'verbose_name': 'Площадка', 'verbose_name_plural': 'Площадки'},
        ),
        migrations.RemoveField(
            model_name='department',
            name='user_id',
        ),
    ]
