# Generated by Django 5.1.1 on 2024-10-13 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0020_alter_field_options_remove_department_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Цех', 'verbose_name_plural': 'Цеха'},
        ),
        migrations.RemoveField(
            model_name='department',
            name='areas_quantity',
        ),
        migrations.AlterField(
            model_name='department',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebSite.field', verbose_name='Название площадки'),
        ),
        migrations.AlterField(
            model_name='department',
            name='indent',
            field=models.IntegerField(default=0, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название цеха'),
        ),
        migrations.AlterField(
            model_name='field',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebSite.company', verbose_name='Название компании'),
        ),
        migrations.AlterField(
            model_name='field',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название площадки'),
        ),
    ]
