# Generated by Django 5.1.1 on 2024-10-13 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0021_alter_department_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subdivision',
            old_name='area_id',
            new_name='area',
        ),
        migrations.RemoveField(
            model_name='department',
            name='operators_quantity',
        ),
        migrations.RemoveField(
            model_name='department',
            name='support_stuff_quantity',
        ),
        migrations.AddField(
            model_name='department',
            name='areas_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество участков'),
        ),
        migrations.AddField(
            model_name='department',
            name='stuff_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество персонала'),
        ),
        migrations.AlterField(
            model_name='department',
            name='machines_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество машин'),
        ),
    ]
