# Generated by Django 5.1.1 on 2024-10-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0022_rename_area_id_subdivision_area_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': '', 'verbose_name_plural': ''},
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название роли'),
        ),
    ]
