# Generated by Django 5.1.1 on 2024-10-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0024_alter_role_options_alter_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Должность'),
        ),
    ]
