# Generated by Django 5.1.1 on 2024-10-13 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0025_alter_role_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name': 'Участок', 'verbose_name_plural': 'Участки'},
        ),
        migrations.AlterField(
            model_name='area',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebSite.department', verbose_name='Название цеха'),
        ),
        migrations.AlterField(
            model_name='area',
            name='indent',
            field=models.IntegerField(default=0, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название участка'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название должности'),
        ),
    ]
