# Generated by Django 5.1.1 on 2024-10-13 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0026_alter_area_options_alter_area_department_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subdivision',
            options={'verbose_name': 'Подразделение', 'verbose_name_plural': 'Подразделения'},
        ),
        migrations.AlterField(
            model_name='subdivision',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebSite.area', verbose_name='Название участка'),
        ),
        migrations.AlterField(
            model_name='subdivision',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Название подразделения'),
        ),
    ]
