# Generated by Django 5.1.1 on 2024-10-13 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0028_alter_subdivision_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdivision',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WebSite.area', verbose_name='Название участка'),
        ),
    ]
