# Generated by Django 5.1.1 on 2024-10-13 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0029_alter_subdivision_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdivision',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='WebSite.area', verbose_name='Название участка'),
        ),
    ]
