# Generated by Django 5.1.1 on 2024-10-14 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0033_user_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='company',
            new_name='company_id',
        ),
    ]
