# Generated by Django 5.1.1 on 2024-10-14 10:39

import PKMSite.yandex_s3_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0034_rename_company_user_company_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='company_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, storage=PKMSite.yandex_s3_storage.ClientImgStorage(), upload_to='', verbose_name='Фотография'),
        ),
    ]
