# Generated by Django 5.1.1 on 2024-10-14 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0035_remove_user_company_id_alter_user_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='stuff_quantity',
        ),
    ]
