# Generated by Django 5.1.2 on 2024-10-15 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0037_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Компания', 'verbose_name_plural': 'Компании'},
        ),
        migrations.AlterField(
            model_name='company',
            name='code',
            field=models.CharField(max_length=100, verbose_name='Код компании'),
        ),
        migrations.AlterField(
            model_name='company',
            name='date_of_end',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания подписки'),
        ),
        migrations.AlterField(
            model_name='company',
            name='date_of_start',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала подписки'),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Оплата'),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_testdrive',
            field=models.BooleanField(default=True, verbose_name='Тестовый период'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название компании'),
        ),
        migrations.AlterField(
            model_name='company',
            name='number_of_support_staff',
            field=models.IntegerField(default=0, verbose_name='Количество персонала'),
        ),
        migrations.AlterField(
            model_name='company',
            name='paid_machines_quantity',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество оплаченных машин'),
        ),
    ]
