# Generated by Django 5.1.1 on 2024-10-08 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PKMBatcharchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=100, unique=True)),
                ('technology_number', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'PKMBatcharchive',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PKMBatchstatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'PKMBatchstatus',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PKMCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=100)),
                ('is_paid', models.BooleanField(blank=True, null=True)),
                ('paid_machines_quantity', models.IntegerField(blank=True, null=True)),
                ('date_of_start', models.DateField()),
                ('date_of_end', models.DateField(blank=True, null=True)),
                ('is_testdrive', models.BooleanField(blank=True, null=True)),
                ('number_of_support_staff', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'PKMCompany',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PKMDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('indent', models.IntegerField(blank=True, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('areas_quantity', models.IntegerField(blank=True, null=True)),
                ('machines_quantity', models.IntegerField(blank=True, null=True)),
                ('operators_quantity', models.IntegerField(blank=True, null=True)),
                ('support_stuff_quantity', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'PKMDepartment',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PKMField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'PKMField',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PKMFirstmachinetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'PKMFirstmachinetype',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PKMOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, unique=True)),
                ('date_receipt', models.DateField()),
                ('required_completion_date', models.DateField()),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('calculated_completion_date', models.DateField(blank=True, null=True)),
                ('actual_completion_date', models.DateField(blank=True, null=True)),
                ('customer', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'PKMOrder',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PKMOrderstatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'PKMOrderstatus',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PKMReporttype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'PKMReporttype',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PKMRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'PKMRole',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PKMSecondmachinetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'PKMSecondmachinetype',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PKMShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'PKMShift',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PKMShiftschedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_change', models.TimeField(blank=True, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('time_first', models.TimeField(blank=True, null=True)),
                ('days', models.IntegerField(blank=True, null=True)),
                ('info', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'PKMShiftschedule',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PKMStagestatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'PKMStagestatus',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PKMVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50)),
                ('link_update', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'PKMVersion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PKMWorkstatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'PKMWorkstatus',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PKMBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('technology', models.TextField(blank=True, null=True)),
                ('isready', models.BooleanField(blank=True, null=True)),
                ('rs_number', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('bath_archive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PKM.pkmbatcharchive')),
                ('batch_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PKM.pkmbatchstatus')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PKM.pkmorder')),
            ],
            options={
                'db_table': 'PKMBatch',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PKMChiefbatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PKM.pkmbatchstatus')),
                ('bath', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PKM.pkmbatch')),
            ],
            options={
                'db_table': 'PKMChiefbatch',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PKMArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('indent', models.IntegerField(blank=True, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PKM.pkmdepartment')),
            ],
            options={
                'db_table': 'PKMArea',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='pkmdepartment',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PKM.pkmfield'),
        ),
        migrations.CreateModel(
            name='PKMDetailmachinetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('first_machine_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PKM.pkmfirstmachinetype')),
            ],
            options={
                'db_table': 'PKMDetailmachinetype',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PKMMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invent_number', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_activated', models.BooleanField(blank=True, null=True)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('prefix', models.CharField(blank=True, max_length=50, null=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PKM.pkmarea')),
                ('detail_machine_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PKM.pkmdetailmachinetype')),
                ('first_machine_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PKM.pkmfirstmachinetype')),
                ('second_machine_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PKM.pkmsecondmachinetype')),
                ('shift_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PKM.pkmshiftschedule')),
            ],
            options={
                'db_table': 'PKMMachine',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='pkmorder',
            name='order_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PKM.pkmorderstatus'),
        ),
        migrations.CreateModel(
            name='PKMStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('isdistributed', models.BooleanField(blank=True, null=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PKM.pkmarea')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PKM.pkmbatch')),
                ('batch_archive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PKM.pkmbatcharchive')),
            ],
            options={
                'db_table': 'PKMStage',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PKMOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('time_pz', models.DurationField(blank=True, null=True)),
                ('time_sh', models.DurationField(blank=True, null=True)),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PKM.pkmstage')),
            ],
            options={
                'db_table': 'PKMOperation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PKMChiefdistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PKM.pkmbatch')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PKM.pkmdepartment')),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PKM.pkmoperation')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PKM.pkmstage')),
            ],
            options={
                'db_table': 'PKMChiefdistribution',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PKMStagearchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('batch_archive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PKM.pkmbatcharchive')),
            ],
            options={
                'db_table': 'PKMStagearchive',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PKMOperationarchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('time_pz', models.DurationField(blank=True, null=True)),
                ('time_sh', models.DurationField(blank=True, null=True)),
                ('stage_archive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PKM.pkmstagearchive')),
            ],
            options={
                'db_table': 'PKMOperationarchive',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PKMStagedistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chief_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PKM.pkmchiefbatch')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PKM.pkmdepartment')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PKM.pkmstage')),
                ('stage_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PKM.pkmstagestatus')),
            ],
            options={
                'db_table': 'PKMStagedistribution',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PKMChiefoperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_distributed', models.BooleanField(blank=True, null=True)),
                ('chief_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PKM.pkmchiefbatch')),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PKM.pkmoperation')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PKM.pkmstage')),
                ('distribution_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PKM.pkmstagedistribution')),
            ],
            options={
                'db_table': 'PKMChiefoperation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PKMOperationoperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_plan', models.DurationField(blank=True, null=True)),
                ('time_first_start', models.DateTimeField(blank=True, null=True)),
                ('time_start', models.DateTimeField(blank=True, null=True)),
                ('time_stop', models.DateTimeField(blank=True, null=True)),
                ('time_working', models.DurationField(blank=True, null=True)),
                ('pause', models.BooleanField(blank=True, null=True)),
                ('optimal_part', models.CharField(blank=True, max_length=255, null=True)),
                ('modific', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PKM.pkmarea')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PKM.pkmbatch')),
                ('chief_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PKM.pkmchiefbatch')),
                ('chief_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PKM.pkmchiefoperation')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PKM.pkmmachine')),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PKM.pkmoperation')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PKM.pkmorder')),
                ('distribution_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PKM.pkmstagedistribution')),
                ('stage_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PKM.pkmstagestatus')),
            ],
            options={
                'db_table': 'PKMOperationoperator',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PKMTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('time_sh', models.DurationField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PKM.pkmoperation')),
            ],
            options={
                'db_table': 'PKMTransfer',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PKMTransferarchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_sh', models.DurationField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('operation_archive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PKM.pkmoperationarchive')),
            ],
            options={
                'db_table': 'PKMTransferarchive',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PKMUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PKM.pkmrole')),
            ],
            options={
                'db_table': 'PKMUser',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PKMUploadedreport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100)),
                ('report_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PKM.pkmreporttype')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PKM.pkmuser')),
            ],
            options={
                'db_table': 'PKMUploadedreport',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PKMTransferoperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_first_start', models.DateTimeField(blank=True, null=True)),
                ('time_start', models.DateTimeField(blank=True, null=True)),
                ('time_stop', models.DateTimeField(blank=True, null=True)),
                ('time_working', models.DurationField(blank=True, null=True)),
                ('pause', models.BooleanField(blank=True, null=True)),
                ('opt_path', models.TextField(blank=True, null=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PKM.pkmbatch')),
                ('chief_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PKM.pkmchiefoperation')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PKM.pkmmachine')),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PKM.pkmoperation')),
                ('operator_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PKM.pkmoperationoperator')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PKM.pkmorder')),
                ('transfer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PKM.pkmtransfer')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PKM.pkmuser')),
            ],
            options={
                'db_table': 'PKMTransferoperation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PKMShiftdistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('change', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PKM.pkmshift')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PKM.pkmmachine')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PKM.pkmuser')),
            ],
            options={
                'db_table': 'PKMShiftdistribution',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='pkmoperationoperator',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PKM.pkmuser'),
        ),
        migrations.CreateModel(
            name='PKMAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PKM.pkmarea')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PKM.pkmrole')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PKM.pkmuser')),
            ],
            options={
                'db_table': 'PKMAllocation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PKMWorkershift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.DateTimeField()),
                ('time_end', models.DateTimeField()),
                ('isactive', models.BooleanField(blank=True, null=True)),
                ('date', models.DateField()),
                ('change', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PKM.pkmshift')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PKM.pkmuser')),
            ],
            options={
                'db_table': 'PKMWorkershift',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PKMMachinework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('stop_time', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('indent', models.IntegerField(blank=True, null=True)),
                ('time_working', models.DurationField(blank=True, null=True)),
                ('isactive', models.BooleanField(blank=True, null=True)),
                ('first_start_batch', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PKM.pkmbatch')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PKM.pkmmachine')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PKM.pkmshift')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PKM.pkmuser')),
                ('work_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PKM.pkmworkstatus')),
            ],
            options={
                'db_table': 'PKMMachinework',
                'managed': True,
            },
        ),
    ]
