# Generated by Django 5.1.1 on 2024-10-08 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NTZBatcharchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=100, unique=True)),
                ('technology_number', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'NTZBatcharchive',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NTZBatchstatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'NTZBatchstatus',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NTZCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=100)),
                ('is_paid', models.BooleanField(blank=True, null=True)),
                ('paid_machines_quantity', models.IntegerField(blank=True, null=True)),
                ('date_of_start', models.DateField()),
                ('date_of_end', models.DateField(blank=True, null=True)),
                ('is_testdrive', models.BooleanField(blank=True, null=True)),
                ('number_of_support_staff', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'NTZCompany',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NTZDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('indent', models.IntegerField(blank=True, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('areas_quantity', models.IntegerField(blank=True, null=True)),
                ('machines_quantity', models.IntegerField(blank=True, null=True)),
                ('operators_quantity', models.IntegerField(blank=True, null=True)),
                ('support_stuff_quantity', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'NTZDepartment',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NTZField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'NTZField',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NTZFirstmachinetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'NTZFirstmachinetype',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NTZOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, unique=True)),
                ('date_receipt', models.DateField()),
                ('required_completion_date', models.DateField()),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('calculated_completion_date', models.DateField(blank=True, null=True)),
                ('actual_completion_date', models.DateField(blank=True, null=True)),
                ('customer', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'NTZOrder',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NTZOrderstatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'NTZOrderstatus',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NTZReporttype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'NTZReporttype',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NTZRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'NTZRole',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NTZSecondmachinetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'NTZSecondmachinetype',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NTZShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'NTZShift',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NTZShiftschedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_change', models.TimeField(blank=True, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('time_first', models.TimeField(blank=True, null=True)),
                ('days', models.IntegerField(blank=True, null=True)),
                ('info', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'NTZShiftschedule',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NTZStagestatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'NTZStagestatus',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NTZVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50)),
                ('link_update', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'NTZVersion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NTZWorkstatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'NTZWorkstatus',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NTZBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('technology', models.TextField(blank=True, null=True)),
                ('isready', models.BooleanField(blank=True, null=True)),
                ('rs_number', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('bath_archive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='NTZ.ntzbatcharchive')),
                ('batch_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='NTZ.ntzbatchstatus')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='NTZ.ntzorder')),
            ],
            options={
                'db_table': 'NTZBatch',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NTZChiefbatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='NTZ.ntzbatchstatus')),
                ('bath', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='NTZ.ntzbatch')),
            ],
            options={
                'db_table': 'NTZChiefbatch',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NTZArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('indent', models.IntegerField(blank=True, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='NTZ.ntzdepartment')),
            ],
            options={
                'db_table': 'NTZArea',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='ntzdepartment',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='NTZ.ntzfield'),
        ),
        migrations.CreateModel(
            name='NTZDetailmachinetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('first_machine_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='NTZ.ntzfirstmachinetype')),
            ],
            options={
                'db_table': 'NTZDetailmachinetype',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NTZMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invent_number', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_activated', models.BooleanField(blank=True, null=True)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('prefix', models.CharField(blank=True, max_length=50, null=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='NTZ.ntzarea')),
                ('detail_machine_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='NTZ.ntzdetailmachinetype')),
                ('first_machine_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='NTZ.ntzfirstmachinetype')),
                ('second_machine_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='NTZ.ntzsecondmachinetype')),
                ('shift_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='NTZ.ntzshiftschedule')),
            ],
            options={
                'db_table': 'NTZMachine',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='ntzorder',
            name='order_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='NTZ.ntzorderstatus'),
        ),
        migrations.CreateModel(
            name='NTZStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('isdistributed', models.BooleanField(blank=True, null=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='NTZ.ntzarea')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='NTZ.ntzbatch')),
                ('batch_archive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='NTZ.ntzbatcharchive')),
            ],
            options={
                'db_table': 'NTZStage',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NTZOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('time_pz', models.DurationField(blank=True, null=True)),
                ('time_sh', models.DurationField(blank=True, null=True)),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='NTZ.ntzstage')),
            ],
            options={
                'db_table': 'NTZOperation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NTZChiefdistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='NTZ.ntzbatch')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='NTZ.ntzdepartment')),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='NTZ.ntzoperation')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='NTZ.ntzstage')),
            ],
            options={
                'db_table': 'NTZChiefdistribution',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NTZStagearchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('batch_archive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='NTZ.ntzbatcharchive')),
            ],
            options={
                'db_table': 'NTZStagearchive',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NTZOperationarchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('time_pz', models.DurationField(blank=True, null=True)),
                ('time_sh', models.DurationField(blank=True, null=True)),
                ('stage_archive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='NTZ.ntzstagearchive')),
            ],
            options={
                'db_table': 'NTZOperationarchive',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NTZStagedistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chief_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='NTZ.ntzchiefbatch')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='NTZ.ntzdepartment')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='NTZ.ntzstage')),
                ('stage_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='NTZ.ntzstagestatus')),
            ],
            options={
                'db_table': 'NTZStagedistribution',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NTZChiefoperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_distributed', models.BooleanField(blank=True, null=True)),
                ('chief_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='NTZ.ntzchiefbatch')),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='NTZ.ntzoperation')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='NTZ.ntzstage')),
                ('distribution_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='NTZ.ntzstagedistribution')),
            ],
            options={
                'db_table': 'NTZChiefoperation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NTZOperationoperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_plan', models.DurationField(blank=True, null=True)),
                ('time_first_start', models.DateTimeField(blank=True, null=True)),
                ('time_start', models.DateTimeField(blank=True, null=True)),
                ('time_stop', models.DateTimeField(blank=True, null=True)),
                ('time_working', models.DurationField(blank=True, null=True)),
                ('pause', models.BooleanField(blank=True, null=True)),
                ('optimal_part', models.CharField(blank=True, max_length=255, null=True)),
                ('modific', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='NTZ.ntzarea')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='NTZ.ntzbatch')),
                ('chief_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='NTZ.ntzchiefbatch')),
                ('chief_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='NTZ.ntzchiefoperation')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='NTZ.ntzmachine')),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='NTZ.ntzoperation')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='NTZ.ntzorder')),
                ('distribution_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='NTZ.ntzstagedistribution')),
                ('stage_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='NTZ.ntzstagestatus')),
            ],
            options={
                'db_table': 'NTZOperationoperator',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NTZTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('time_sh', models.DurationField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='NTZ.ntzoperation')),
            ],
            options={
                'db_table': 'NTZTransfer',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NTZTransferarchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_sh', models.DurationField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('operation_archive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='NTZ.ntzoperationarchive')),
            ],
            options={
                'db_table': 'NTZTransferarchive',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NTZUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='NTZ.ntzrole')),
            ],
            options={
                'db_table': 'NTZUser',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NTZUploadedreport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100)),
                ('report_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='NTZ.ntzreporttype')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='NTZ.ntzuser')),
            ],
            options={
                'db_table': 'NTZUploadedreport',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NTZTransferoperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_first_start', models.DateTimeField(blank=True, null=True)),
                ('time_start', models.DateTimeField(blank=True, null=True)),
                ('time_stop', models.DateTimeField(blank=True, null=True)),
                ('time_working', models.DurationField(blank=True, null=True)),
                ('pause', models.BooleanField(blank=True, null=True)),
                ('opt_path', models.TextField(blank=True, null=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='NTZ.ntzbatch')),
                ('chief_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='NTZ.ntzchiefoperation')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='NTZ.ntzmachine')),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='NTZ.ntzoperation')),
                ('operator_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='NTZ.ntzoperationoperator')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='NTZ.ntzorder')),
                ('transfer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='NTZ.ntztransfer')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='NTZ.ntzuser')),
            ],
            options={
                'db_table': 'NTZTransferoperation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NTZShiftdistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('change', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='NTZ.ntzshift')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='NTZ.ntzmachine')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='NTZ.ntzuser')),
            ],
            options={
                'db_table': 'NTZShiftdistribution',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='ntzoperationoperator',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='NTZ.ntzuser'),
        ),
        migrations.CreateModel(
            name='NTZAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='NTZ.ntzarea')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='NTZ.ntzrole')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='NTZ.ntzuser')),
            ],
            options={
                'db_table': 'NTZAllocation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NTZWorkershift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.DateTimeField()),
                ('time_end', models.DateTimeField()),
                ('isactive', models.BooleanField(blank=True, null=True)),
                ('date', models.DateField()),
                ('change', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='NTZ.ntzshift')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='NTZ.ntzuser')),
            ],
            options={
                'db_table': 'NTZWorkershift',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NTZMachinework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('stop_time', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('indent', models.IntegerField(blank=True, null=True)),
                ('time_working', models.DurationField(blank=True, null=True)),
                ('isactive', models.BooleanField(blank=True, null=True)),
                ('first_start_batch', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='NTZ.ntzbatch')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='NTZ.ntzmachine')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='NTZ.ntzshift')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='NTZ.ntzuser')),
                ('work_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='NTZ.ntzworkstatus')),
            ],
            options={
                'db_table': 'NTZMachinework',
                'managed': True,
            },
        ),
    ]
